# Generated by Django 4.1.6 on 2023-02-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
    ]
